-- MySQL Script generated by MySQL Workbench
-- Tue Nov  5 20:51:21 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bips_wise24
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bips_wise24
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bips_wise24` DEFAULT CHARACTER SET utf8 ;
USE `bips_wise24` ;

-- -----------------------------------------------------
-- Table `bips_wise24`.`fragebogen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bips_wise24`.`fragebogen` (
  `id_fragebogen` INT NOT NULL,
  `beschreibung` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_fragebogen`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bips_wise24`.`projekt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bips_wise24`.`projekt` (
  `id_projekt` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `komponente` VARCHAR(100) NOT NULL,
  `id_fragebogen` INT NOT NULL,
  PRIMARY KEY (`id_projekt`),
  INDEX `fk_Projekt_Fragebogen1_idx` (`id_fragebogen` ASC) VISIBLE,
  CONSTRAINT `fk_Projekt_Fragebogen1`
    FOREIGN KEY (`id_fragebogen`)
    REFERENCES `bips_wise24`.`fragebogen` (`id_fragebogen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bips_wise24`.`lieferant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bips_wise24`.`lieferant` (
  `id_lieferant` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(45) NOT NULL,
  `passwort` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_lieferant`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bips_wise24`.`kategorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bips_wise24`.`kategorie` (
  `id_kategorie` INT NOT NULL,
  `beschreibung` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_kategorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bips_wise24`.`frage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bips_wise24`.`frage` (
  `id_frage` INT NOT NULL,
  `fragetext` VARCHAR(450) NOT NULL,
  `id_kategorie` INT NOT NULL,
  PRIMARY KEY (`id_frage`),
  INDEX `fk_Frage_Kategorie1_idx` (`id_kategorie` ASC) VISIBLE,
  CONSTRAINT `fk_Frage_Kategorie1`
    FOREIGN KEY (`id_kategorie`)
    REFERENCES `bips_wise24`.`kategorie` (`id_kategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bips_wise24`.`antwort`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bips_wise24`.`antwort` (
  `id_antwort` INT NOT NULL,
  `id_frage` INT NOT NULL,
  `antworttext` VARCHAR(250) NOT NULL,
  `punkte` INT NOT NULL,
  PRIMARY KEY (`id_antwort`, `id_frage`),
  INDEX `fk_Antwort_Frage1_idx` (`id_frage` ASC) VISIBLE,
  CONSTRAINT `fk_Antwort_Frage1`
    FOREIGN KEY (`id_frage`)
    REFERENCES `bips_wise24`.`frage` (`id_frage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bips_wise24`.`fragebogen_has_frage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bips_wise24`.`fragebogen_has_frage` (
  `id_fragebogen` INT NOT NULL,
  `id_frage` INT NOT NULL,
  PRIMARY KEY (`id_fragebogen`, `id_frage`),
  INDEX `fk_Fragebogen_has_Frage_Frage1_idx` (`id_frage` ASC) VISIBLE,
  INDEX `fk_Fragebogen_has_Frage_Fragebogen_idx` (`id_fragebogen` ASC) VISIBLE,
  CONSTRAINT `fk_Fragebogen_has_Frage_Fragebogen`
    FOREIGN KEY (`id_fragebogen`)
    REFERENCES `bips_wise24`.`fragebogen` (`id_fragebogen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fragebogen_has_Frage_Frage1`
    FOREIGN KEY (`id_frage`)
    REFERENCES `bips_wise24`.`frage` (`id_frage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bips_wise24`.`projekt_has_lieferant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bips_wise24`.`projekt_has_lieferant` (
  `id_projekt` INT NOT NULL,
  `id_lieferant` INT NOT NULL,
  `score` FLOAT NULL,
  `rank` INT NULL,
  PRIMARY KEY (`id_projekt`, `id_lieferant`),
  INDEX `fk_Projekt_has_Lieferant_Lieferant1_idx` (`id_lieferant` ASC) VISIBLE,
  INDEX `fk_Projekt_has_Lieferant_Projekt1_idx` (`id_projekt` ASC) VISIBLE,
  CONSTRAINT `fk_Projekt_has_Lieferant_Projekt1`
    FOREIGN KEY (`id_projekt`)
    REFERENCES `bips_wise24`.`projekt` (`id_projekt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Projekt_has_Lieferant_Lieferant1`
    FOREIGN KEY (`id_lieferant`)
    REFERENCES `bips_wise24`.`lieferant` (`id_lieferant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bips_wise24`.`projekt_has_lieferant_has_antwort`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bips_wise24`.`projekt_has_lieferant_has_antwort` (
  `id_projekt` INT NOT NULL,
  `id_lieferant` INT NOT NULL,
  `id_frage` INT NOT NULL,
  `id_antwort` INT NOT NULL,
  PRIMARY KEY (`id_projekt`, `id_lieferant`, `id_frage`, `id_antwort`),
  INDEX `fk_Projekt_has_Lieferant_has_Antwort_Antwort1_idx` (`id_antwort` ASC, `id_frage` ASC) VISIBLE,
  INDEX `fk_Projekt_has_Lieferant_has_Antwort_Projekt_has_Lieferant1_idx` (`id_projekt` ASC, `id_lieferant` ASC) VISIBLE,
  CONSTRAINT `fk_Projekt_has_Lieferant_has_Antwort_Projekt_has_Lieferant1`
    FOREIGN KEY (`id_projekt` , `id_lieferant`)
    REFERENCES `bips_wise24`.`projekt_has_lieferant` (`id_projekt` , `id_lieferant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Projekt_has_Lieferant_has_Antwort_Antwort1`
    FOREIGN KEY (`id_antwort` , `id_frage`)
    REFERENCES `bips_wise24`.`antwort` (`id_antwort` , `id_frage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bips_wise24`.`kategoriegewicht_in_projekt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bips_wise24`.`kategoriegewicht_in_projekt` (
  `id_kategorie` INT NOT NULL,
  `id_projekt` INT NOT NULL,
  `gewicht` FLOAT NOT NULL,
  PRIMARY KEY (`id_kategorie`, `id_projekt`),
  INDEX `fk_Kategorie_has_Projekt_Projekt1_idx` (`id_projekt` ASC) VISIBLE,
  INDEX `fk_Kategorie_has_Projekt_Kategorie1_idx` (`id_kategorie` ASC) VISIBLE,
  CONSTRAINT `fk_Kategorie_has_Projekt_Kategorie1`
    FOREIGN KEY (`id_kategorie`)
    REFERENCES `bips_wise24`.`kategorie` (`id_kategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Kategorie_has_Projekt_Projekt1`
    FOREIGN KEY (`id_projekt`)
    REFERENCES `bips_wise24`.`projekt` (`id_projekt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bips_wise24`.`projekt_has_antwort`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bips_wise24`.`projekt_has_antwort` (
  `id_projekt` INT NOT NULL,
  `id_antwort` INT NOT NULL,
  `id_frage` INT NOT NULL,
  `ist_ko_kriterium` TINYINT NOT NULL,
  PRIMARY KEY (`id_projekt`, `id_antwort`, `id_frage`),
  INDEX `fk_Projekt_has_Antwort_Antwort1_idx` (`id_antwort` ASC, `id_frage` ASC) VISIBLE,
  INDEX `fk_Projekt_has_Antwort_Projekt1_idx` (`id_projekt` ASC) VISIBLE,
  CONSTRAINT `fk_Projekt_has_Antwort_Projekt1`
    FOREIGN KEY (`id_projekt`)
    REFERENCES `bips_wise24`.`projekt` (`id_projekt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Projekt_has_Antwort_Antwort1`
    FOREIGN KEY (`id_antwort` , `id_frage`)
    REFERENCES `bips_wise24`.`antwort` (`id_antwort` , `id_frage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
